const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('App/public/index.html','utf8');
const context=vm.createContext({Date,console});
vm.runInContext(html.slice(html.indexOf('const GOLD_PRODUCTS='),html.indexOf('const METAL_SYMBOLS='))+html.slice(html.indexOf('let pendingSmartCameraSuggestion='),html.indexOf('function smartCameraConfidenceLabel')),context);
const scan=(text,extra={})=>context.interpretSmartCameraScan({text,confidence:.95,...extra});
let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}
test('Actual failed Maple OCR resolves silver profile',()=>{const r=scan('CAN 9999 9999 ARGENT PUR SINE STLVERN SILV');assert.equal(r.metal,'silver');assert.equal(r.product,'Canadian Silver Maple Leaf');assert.equal(r.weight,0);assert.equal(r.usable,true)});
test('Complete Maple inscription reads 1 oz',()=>{const r=scan('C A N A D A 9999 FINE SILVER 1 OZ ARGENT PUR');assert.equal(r.product,'Canadian Silver Maple Leaf');assert.equal(r.weight,1)});
test('Warm color and generic labels never determine metal',()=>{const r=scan('',{visualColor:{tone:'golden'},visualLabels:[{identifier:'eagle',confidence:.99}]});assert.equal(r.metal,'');assert.equal(r.product,'');assert.equal(r.usable,false)});
test('Truncated Eagle date is not invented',()=>{const r=scan('11 IN GOD WE TRUST');assert.equal(r.year,null);assert.equal(r.product,'');assert.equal(r.usable,false)});
test('Full date survives even without metal',()=>assert.equal(scan('LIBERTY 2011 IN GOD WE TRUST').year,2011));
test('Combined Eagle reverse and date match',()=>{const r=scan('LIBERTY 2011 IN GOD WE TRUST UNITED STATES OF AMERICA 1 OZ FINE SILVER ONE DOLLAR',{sides:2});assert.equal(r.product,'American Silver Eagle');assert.equal(r.weight,1);assert.equal(r.year,2011);assert.equal(r.sides,2)});
test('Generic silver ounce does not invent Eagle',()=>assert.equal(scan('1 oz fine silver .999').product,''));
test('Generic gold ounce does not invent Eagle or Buffalo',()=>assert.equal(scan('1 oz fine gold .9999').product,''));
test('Fractional gold Eagle does not default to one ounce',()=>assert.equal(scan('American Gold Eagle 1/10 oz fine gold').weight,.1));
test('Gold Eagle without weight leaves it blank',()=>assert.equal(scan('American Gold Eagle').weight,0));
test('Ambiguous Maple metal stays unknown',()=>{const r=scan('Maple Leaf Canada 9999');assert.equal(r.metal,'');assert.equal(r.product,'');assert.equal(r.usable,false)});
test('Gold and silver evidence blocks use',()=>{const r=scan('Fine silver 1 oz Fine gold');assert.equal(r.metal,'');assert.equal(r.usable,false)});
test('Conflicting weights block use and leave weight blank',()=>{const r=scan('Fine silver 1 oz 10 oz');assert.equal(r.weight,0);assert.equal(r.usable,false)});
test('Matched fixed specification disagreement blocks use',()=>{const r=scan('American Silver Eagle 1/2 oz');assert.equal(r.weight,0);assert.equal(r.usable,false)});
test('Plated and replicas block use',()=>{for(const s of ['gold plated','silver replica','gold filled'])assert.equal(scan(s+' 1 oz').usable,false)});
test('Gram and equivalent ounce deduplicate',()=>{const r=scan('fine gold 31.1035 g 1 oz');assert.ok(Math.abs(r.weight-1)<.001);assert.equal(r.warnings.length,0)});
test('Multilingual metal evidence',()=>{for(const text of ['argent pur','plata pura','feinsilber'])assert.equal(scan(text).metal,'silver');assert.equal(scan('oro puro').metal,'gold');assert.equal(scan('platine').metal,'platinum')});
test('Fraction and written ounce parsing',()=>{assert.equal(scan('fine silver ONE TROY OUNCE').weight,1);assert.equal(scan('fine gold 1/4 oz').weight,.25);assert.equal(scan('fine gold ½ oz').weight,.5)});
test('Kilogram parsing',()=>assert.ok(Math.abs(scan('fine silver 1 kg').weight-32.1507466)<.0001));
test('Purity by itself does not determine metal',()=>assert.equal(scan('9999 1 oz').usable,false));
test('Multiple dates leave year blank',()=>assert.equal(scan('fine silver 2011 2012').year,null));
test('Mint contradiction blocks use',()=>assert.equal(scan('American Silver Eagle Perth Mint').usable,false));
test('Historic Britannia purity is not assumed',()=>assert.equal(scan('Britannia Gold 1990').purity,''));
test('Serial retained literally',()=>assert.equal(scan('Valcambi Fine Gold Serial: AB12345 10 g').serial,'AB12345'));
test('Generic half dollar does not invent a historic product',()=>assert.equal(scan('Half dollar 1964').product,''));
test('Canada silver bar is not mistaken for Maple Leaf',()=>assert.equal(scan('Canada Fine Silver 9999 10 oz Bar').product,'Silver Bar'));
test('Split four-digit date is recovered without guessing',()=>assert.equal(scan('LIBERTY 2 0 1 1').year,2011));
test('Conflicting purity blocks use',()=>assert.equal(scan('Fine silver .999 .900 1 oz').usable,false));
test('Fixed product fineness contradiction blocks use',()=>assert.equal(scan('American Silver Eagle .925').usable,false));
test('Unrelated serial digits cannot create purity',()=>assert.equal(scan('Fine gold Serial: AB9999123').purity,''));
console.log(count+' scanner regression checks passed');
