const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('App/public/index.html','utf8');
const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{value:'old',disabled:false,textContent:'',options:[],selectedIndex:0,classList:{values:new Set(),add(v){this.values.add(v)},remove(v){this.values.delete(v)},contains(v){return this.values.has(v)}},setAttribute(){}});return nodes.get(id)};
let queued=[],calls=[],resetCalls=0,resetHook=async()=>{};const plugin={reset:async()=>{resetCalls++;await resetHook();},scan:async options=>{calls.push(options);return await queued.shift()}};
const context=vm.createContext({Date,console,document:{getElementById:get,querySelectorAll:()=>[get('smartAnalysisUseButton')]},
  isProActive:()=>true,isBenzaNativeRuntime:()=>true,smartCameraPlugin:()=>plugin,ensureGlobalAddPortals(){},closeAddChoice(){},isFounderPro:()=>false,openAdd(){},selectMetal(){},update(){}});
vm.runInContext(html.slice(html.indexOf('const GOLD_PRODUCTS='),html.indexOf('const METAL_SYMBOLS='))+html.slice(html.indexOf('let pendingSmartCameraSuggestion='),html.indexOf('function clearAttachmentObjectUrls')),context);
vm.runInContext('renderSmartCameraAnalysis=(suggestion)=>{pendingSmartCameraSuggestion=suggestion;globalThis.lastSuggestion=suggestion;}',context);
const reset=()=>vm.runInContext('smartCameraScans=[];smartCameraPhotoCount=0;pendingSmartCameraSuggestion=null;',context);
const pending=()=>vm.runInContext('pendingSmartCameraSuggestion',context);
const views=()=>vm.runInContext('smartCameraScans.length',context);
let count=0;async function test(name,fn){await fn();count++;console.log('PASS',name)}
(async()=>{
 await test('Reverse merges same-item year and markings',async()=>{queued.push({text:'LIBERTY 2011',confidence:.9},{text:'UNITED STATES OF AMERICA 1 OZ FINE SILVER ONE DOLLAR',confidence:.9});await context.runSmartCameraScan();await context.runSmartCameraScan(true);assert.equal(context.lastSuggestion.year,2011);assert.equal(context.lastSuggestion.product,'American Silver Eagle');assert.equal(context.lastSuggestion.sides,2)});
 await test('New item does not inherit prior date or metal',async()=>{queued.push({text:'Fine gold 10 g',confidence:.9});await context.runSmartCameraScan();assert.equal(context.lastSuggestion.metal,'gold');assert.equal(context.lastSuggestion.year,null);assert.equal(context.lastSuggestion.sides,1)});
 await test('Cancellation retains previous result',async()=>{const before=context.lastSuggestion;queued.push({cancelled:true});await context.runSmartCameraScan(true);assert.equal(context.lastSuggestion,before);assert.equal(pending(),before)});
 await test('Library option reaches native photo picker',async()=>{queued.push({text:'argent pur 1 oz',confidence:.9});await context.runSmartCameraScan(false,'library');assert.equal(calls.at(-1).source,'library')});
 await test('Double tap calls native only once',async()=>{let done;queued.push(new Promise(resolve=>done=resolve));const first=context.runSmartCameraScan();await new Promise(resolve=>setImmediate(resolve));const n=calls.length;await context.runSmartCameraScan();assert.equal(calls.length,n);assert.equal(get('smartAnalysisUseButton').disabled,true);done({text:'Fine silver',confidence:.9});await first});
 await test('Closing prevents late result from being applied',async()=>{let done;const before=context.lastSuggestion;queued.push(new Promise(resolve=>done=resolve));const first=context.runSmartCameraScan();await new Promise(resolve=>setImmediate(resolve));context.closeSmartCamera();done({text:'Fine gold',confidence:.9});await first;assert.equal(context.lastSuggestion,before)});
 await test('Unknown product and weight clear preexisting form defaults',async()=>{get('weight').value='1';get('product').selectedIndex=0;assert.equal(context.applySmartCameraSuggestion(context.interpretSmartCameraScan({text:'Fine silver',confidence:.9})),true);assert.equal(get('weight').value,'');assert.equal(get('product').selectedIndex,-1)});
 await test('Unsupported suggestion cannot open or fill form',async()=>{get('weight').value='sentinel';assert.equal(context.applySmartCameraSuggestion(context.interpretSmartCameraScan({text:'',visualColor:{tone:'golden'}})),false);assert.equal(get('weight').value,'sentinel')});
 await test('Reverse metal contradiction blocks suggestion',async()=>{reset();queued.push({text:'Fine silver',confidence:.9},{text:'Fine gold',confidence:.9});await context.runSmartCameraScan();await context.runSmartCameraScan(true);assert.equal(context.lastSuggestion.usable,false);assert.equal(get('smartAnalysisUseButton').disabled,true)});

 await test('New item clears existing details before camera opens',async()=>{queued.push({text:'fine silver 2011 1 oz',confidence:.9});await context.runSmartCameraScan();let done;queued.push(new Promise(resolve=>done=resolve));const next=context.runSmartCameraScan();assert.equal(pending(),null);assert.equal(views(),0);await new Promise(resolve=>setImmediate(resolve));done({cancelled:true});await next;assert.equal(pending(),null);assert.equal(get('smartAnalysisUseButton').disabled,true)});
 await test('Failed fresh scan cannot resurrect old suggestion',async()=>{queued.push({text:'fine gold 1 oz',confidence:.9});await context.runSmartCameraScan();const oldConsole=context.console;context.console={...console,error(){}};queued.push(Promise.reject(Error('Camera failure')));await context.runSmartCameraScan();context.console=oldConsole;assert.equal(pending(),null);assert.equal(views(),0);assert.equal(get('smartAnalysisUseButton').disabled,true)});
 await test('Blank reverse does not stack or reduce evidence',async()=>{queued.push({text:'fine silver 1 oz .999',confidence:.95});await context.runSmartCameraScan();const before=pending();queued.push({lines:[],confidence:0});await context.runSmartCameraScan(true);assert.equal(pending(),before);assert.equal(views(),1);assert.equal(get('smartAnalysisUseButton').disabled,false)});
 await test('Noise-only reverse is ignored',async()=>{queued.push({text:'fine silver 1 oz .999',confidence:.95});await context.runSmartCameraScan();const before=pending();queued.push({text:'art textile',confidence:.1});await context.runSmartCameraScan(true);assert.equal(pending(),before);assert.equal(views(),1)});
 await test('Lower confidence detail cannot reduce prior good evidence',async()=>{queued.push({text:'fine silver 1 oz .999',confidence:.95});await context.runSmartCameraScan();const before=pending().confidence;queued.push({text:'2011',confidence:.25});await context.runSmartCameraScan(true);assert.ok(pending().confidence>=before)});
 await test('Two-side limit preserves the first side',async()=>{queued.push({text:'2011',confidence:.9},{text:'Fine silver 1 oz',confidence:.9});await context.runSmartCameraScan();await context.runSmartCameraScan(true);const n=calls.length;await context.runSmartCameraScan(true);assert.equal(calls.length,n);assert.equal(views(),2);assert.equal(pending().year,2011)});
 await test('Explicit reset clears results and calls native reset',async()=>{const n=resetCalls;await context.resetSmartCameraScan();assert.equal(resetCalls,n+1);assert.equal(pending(),null);assert.equal(views(),0);assert.equal(get('smartAnalysisUseButton').disabled,true)});
 await test('Reset waits for native cleanup before enabling a new scan',async()=>{let done;resetHook=()=>new Promise(resolve=>done=resolve);const reset=context.resetSmartCameraScan();const n=calls.length;await context.runSmartCameraScan();assert.equal(calls.length,n);assert.equal(get('smartCameraProButton').disabled,true);done();await reset;resetHook=async()=>{};assert.equal(get('smartCameraProButton').disabled,false)});
 await test('Abandoned callback cannot unlock a newer operation',async()=>{let oldDone;queued.push(new Promise(resolve=>oldDone=resolve));const oldScan=context.runSmartCameraScan();await new Promise(resolve=>setImmediate(resolve));await context.resetSmartCameraScan();let newDone;queued.push(new Promise(resolve=>newDone=resolve));const newScan=context.runSmartCameraScan();await new Promise(resolve=>setImmediate(resolve));oldDone({text:'Fine gold',confidence:.9});await oldScan;assert.equal(get('smartCameraProButton').disabled,true);assert.equal(pending(),null);newDone({text:'Fine silver',confidence:.9});await newScan;assert.equal(pending().metal,'silver');assert.equal(get('smartCameraProButton').disabled,false)});
 await test('Twenty consecutive new items never mix evidence',async()=>{for(let i=0;i<20;i++){const metal=i%2?'gold':'silver';queued.push({text:'Fine '+metal+' 1 oz '+(i%2?'2020':'2011'),confidence:.9});await context.runSmartCameraScan();assert.equal(pending().metal,metal);assert.equal(pending().year,i%2?2020:2011);assert.equal(views(),1)}});
 await test('Unmarked front asks for the reverse without inventing evidence',async()=>{queued.push({lines:[],confidence:0});await context.runSmartCameraScan();assert.equal(views(),0);assert.equal(pending().sides,1);assert.equal(pending().usable,false)});
 await test('Unmarked front plus readable reverse counts as two photos',async()=>{queued.push({text:'fine silver 1 oz',confidence:.9});await context.runSmartCameraScan(true);assert.equal(pending().sides,2);assert.equal(views(),1)});
 await test('Two blank photos stop reverse retries',async()=>{queued.push({lines:[]},{lines:[]});await context.runSmartCameraScan();await context.runSmartCameraScan(true);assert.equal(vm.runInContext('smartCameraAwaitingReverse',context),false);const n=calls.length;await context.runSmartCameraScan(true);assert.equal(calls.length,n);assert.equal(views(),0);assert.equal(get('smartAnalysisTitle').textContent,'I couldn’t identify this confidently')});
 await test('Reset failure does not report success or retain evidence',async()=>{resetHook=async()=>{throw Error('Reset failed')};assert.equal(await context.resetSmartCameraScan(true),false);resetHook=async()=>{};assert.equal(pending(),null);assert.equal(views(),0);assert.equal(get('smartCameraStatus').textContent,'Please close and reopen the scanner.')});
 await test('Opening after failed reset never opens camera',async()=>{resetHook=async()=>{throw Error('Reset failed')};const n=calls.length;await context.openSmartCamera();resetHook=async()=>{};assert.equal(calls.length,n)});
 await test('Reopening while an older reset finishes starts only the newest capture',async()=>{let done;let first=true;resetHook=async()=>{if(first){first=false;await new Promise(resolve=>done=resolve)}};const n=calls.length;const oldOpen=context.openSmartCamera();await new Promise(resolve=>setImmediate(resolve));context.closeSmartCamera();queued.push({cancelled:true});await context.openSmartCamera();done();await oldOpen;resetHook=async()=>{};assert.equal(calls.length,n+1)});
 console.log(count+' scanner flow checks passed');
})().catch(error=>{console.error(error);process.exitCode=1});
